### ISSUE TITLE
[EoN 5.2] Bug héritage des contacts

### ISSUE THREAD

**Issue by JeromeTeam** [EyesOfNetworkCommunity/lilac#25]
Bonjour,
Je rencontre actuellement un bug critique sur l’héritage des contacts (de notification) sous EoN 5.2.
A partir de l’espace de configuration EoN, l’ajout d’un groupe de contacts  à un service écrase les contacts hérités d’un template de service.
Y' a t'il un fix s'il vous plait pour ce problème ?
Avez-vous rencontré ce comportement ?
Par avance merci.

**Configuration** 
![configuration](https://user-images.githubusercontent.com/23382494/95057977-2a390200-06f7-11eb-96e2-b7788eb565ad.png)

**Fichier de configuration 5.2**
On perd les groupes de la partie « Contact Group Inherit »
![erreur_5_2](https://user-images.githubusercontent.com/23382494/95058541-f6aaa780-06f7-11eb-93cd-356fc487fa94.png)

**Fichier de configuration 5.1**
Où nous n’avons pas la régression
![erreur_5_1](https://user-images.githubusercontent.com/23382494/95058561-fca08880-06f7-11eb-9a86-353eff6f058e.png)

**Comment by OscarPoels** [comment]
Bonjour Jérome,
Je pense que vous avez simplement fait une mauvaise interprétation des fichiers de configuration.
Ce n’est pas un bug, c’est juste que les fichiers de configuration entre Eon 5.1 et 5.2 ne sont pas les mêmes. En effet dans la version d’Eon 5.2, les « Contact Group Inehrit » ne sont plus présent dans le fichier de configuration de l’host (où vous pouvez également consulter les services), seuls les « Contact Group Explicit » sont affichés. Vous remarquerez que même lorsqu’aucun « Contact Group Explicit » n’est présent, rien n’est affiché dans le-dis fichier. Le fait d’ajouter un « Contact Group Explicit » au service n’écrase donc normalement pas les « Contact Group Inehrit ». Vous pouvez tout de même constater via votre tableau de bord que les « Contact Group Inehrit » sont bel et bien pris en compte.


On voit bien que je dispose de groupes qui sont hérités d’une template :
<img width="786" alt="screen 1" src="https://user-images.githubusercontent.com/28846880/95593655-41a32280-0a4a-11eb-8f6a-97af32a0d683.PNG">



On peut remarquer qu’ils ne sont pas présent dans le fichier de configuration en question :
<img width="293" alt="screen 2" src="https://user-images.githubusercontent.com/28846880/95593682-48319a00-0a4a-11eb-8f52-8dd8982e62a0.PNG">



Seulement les « Contact Group Explicit » le sont :
<img width="801" alt="screen 3" src="https://user-images.githubusercontent.com/28846880/95593710-51226b80-0a4a-11eb-825c-16ae8c034cc0.PNG">
(Noté que le service se nomme bien eyesofnetwork)
J’y ajoute un « Contact Group Explicit » :

<img width="774" alt="screen 4" src="https://user-images.githubusercontent.com/28846880/95593726-567fb600-0a4a-11eb-9bd0-764e088e2277.PNG">



Il est bien présent dans le fichier de configuration :
<img width="293" alt="screen 5" src="https://user-images.githubusercontent.com/28846880/95593744-5b446a00-0a4a-11eb-80e5-231874ac3ec7.PNG">



Pour preuve qu’ajouter un groupe à un service n’écrase pas les groupes hérité de la template (comme vous l’avez vu sur le screen précédent, j’ai ajouté un « Contact Group Explicit » :
Le groupe « test » contient bien le membre » test » :
<img width="791" alt="screen 6" src="https://user-images.githubusercontent.com/28846880/95593759-60091e00-0a4a-11eb-8c28-80755ef7ba08.PNG">



Mes informations remontent donc bien au membre « test » qui appartient au groupe « test » :
<img width="949" alt="screen 7" src="https://user-images.githubusercontent.com/28846880/95593783-68615900-0a4a-11eb-8445-38cd0592674f.PNG">

Etant donné que les « Contact Group Inehrit » ne sont pas présent dans ce fichier, vous pouvez toujours voir apparaitre la template associée :
<img width="287" alt="screen 8" src="https://user-images.githubusercontent.com/28846880/95593799-6eefd080-0a4a-11eb-8022-cd27af03b491.PNG">


Et ainsi aller chercher dans le fichier de configuration de la template les groupes associés (qui devrait se trouver dans srv/eyesofnetwork/nagios/etc/objects/servicetemplates):
<img width="305" alt="screen 9" src="https://user-images.githubusercontent.com/28846880/95593824-73b48480-0a4a-11eb-91e6-25809e48cecd.PNG">


En espérant avoir répondu à votre question
Excellente journée
